name : CI

on : 
  push:
    branches: 
      - main
    paths: ""
  pull_request:
  workflow_dispatch:
  
jobs:
  test:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
          python-version: ["3.7", "3.8", "3.9"]

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
        
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          
      #specify python version here
      
      - name : load dependencies
        id: init_env
        run: python3 -m venv work_env | pip install -r requirements.txt 
        
      - name : Run tests with pytests
        run: echo "Running Tests" |
              pytest tests/
        
      

#Running tests on changes to code
#Model retraining on changes to data
#Deployment on changes to model artifacts


  #- name: Install dependencies

  #- name: Test with pytest
  
